kind: pipeline
name: default

workspace:
  path: /home/node/app

steps:
  - name: build
    image: node:20.13.0
    volumes:
      - name: yarncache
        path: /usr/local/share/.cache/yarn
    commands:
      - yarn
      - yarn build
    environment:
      CI: false

  - name: deploy
    image: alpine:3.20
    volumes:
      - name: webroot
        path: /webroot
    commands:
      - mkdir -p /webroot/blog/
      - rm -rf /webroot/blog/*
      - cp -rf ./public/* /webroot/blog/

  - name: deploy-cdn
    image: node:20.13.0
    commands:
      - yarn deploy
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: COS_SECRET_ID
      AWS_SECRET_ACCESS_KEY:
        from_secret: COS_SECRET_KEY

  - name: baidu-push
    image: curlimages/curl
    failure: ignore
    commands:
      - cd ./public
      - curl -s -H 'Content-Type:text/plain' --data-binary @sitemap.txt "http://data.zz.baidu.com/urls?site=https://paperplane.cc&token=$BAIDU_ZHANZHANG_TOKEN"
    environment:
      BAIDU_ZHANZHANG_TOKEN:
        from_secret: BAIDU_ZHANZHANG_TOKEN

volumes:
  - name: webroot
    host:
      path: /root/www
  - name: yarncache
    host:
      path: /root/.yarncache

trigger:
  branch:
    - master
