kind: pipeline
name: default

workspace:
  path: /paperplane-blog

volumes:
  - name: webroot
    host:
      path: /root/www
  - name: pnpm-cache
    host:
      path: /root/.pnpm-cache

trigger:
  branch:
    - master

steps:
  - name: build
    image: paperplanecc/baseline-node20:2025.11.30
    volumes:
      - name: pnpm-cache
        path: /paperplane-blog/.pnpm-store
    commands:
      - pnpm i
      - pnpm build
    environment:
      PAPAERPLANE_API_ADMIN_HEADER_NAME:
        from_secret: PAPAERPLANE_API_ADMIN_HEADER_NAME
      PAPAERPLANE_API_ADMIN_HEADER_VALUE:
        from_secret: PAPAERPLANE_API_ADMIN_HEADER_VALUE

  - name: deploy-upload-cdn
    image: plugins/s3
    settings:
      endpoint:
        from_secret: S3_ENDPOINT
      region:
        from_secret: S3_REGION
      bucket:
        from_secret: S3_BUCKET_NAME
      access_key:
        from_secret: S3_ACCESS_KEY_ID
      secret_key:
        from_secret: S3_SECRET_ACCESS_KEY
      source: ./public/**/*
      target: /paperplane-blog
      strip_prefix: public

  - name: deploy
    image: alpine:3.20
    volumes:
      - name: webroot
        path: /webroot
    commands:
      - mkdir -p /webroot/paperplane-blog/
      - rm -rf /webroot/paperplane-blog/*
      - cp -rf ./public/* /webroot/paperplane-blog/

  - name: baidu-push
    image: curlimages/curl
    failure: ignore
    commands:
      - cd ./public
      - curl -s -H 'Content-Type:text/plain' --data-binary @sitemap.txt "http://data.zz.baidu.com/urls?site=https://paperplane.cc&token=$BAIDU_ZHANZHANG_TOKEN"
    environment:
      BAIDU_ZHANZHANG_TOKEN:
        from_secret: BAIDU_ZHANZHANG_TOKEN
